=== mergeorge/CIA/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="Company">
	<xs:complexType>
	    <xs:sequence>
	        <xs:element name="employee" maxOccurs="unbounded">
	        	<xs:complexType>
				    <xs:sequence>
						<xs:element name="emp-name" type="xs:string"/>
						<xs:element name="emp-age" type="xs:integer"/>
				        <xs:element name="emp-salary" type="ty"/>
				        <xs:element name="emp-email" type="xs:string"/>
				        <xs:element name="emp-phone" type="xs:integer"/>
						<xs:element name="designation" type="xs:string"/>
				    </xs:sequence>
				</xs:complexType>
	        </xs:element>
	    </xs:sequence>
	    <xs:attribute name= 'EMPID' type="xs:ID" use="required"/>
	</xs:complexType>
</xs:element>
<xs:simpleType name="ty">
<xs:restriction base="xs:integer">
<xs:minExclusive value="50000"></xs:minExclusive>
<xs:maxExclusive value="200000"></xs:maxExclusive>
</xs:restriction>


</xs:simpleType>
</xs:schema>

=== mergeorge/CIA/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="employee.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="employee.xsd"> 
	
	   
		    <employee EMPID="Emp01">
		    <emp-name>Merin George</emp-name>
		<emp-age>35</emp-age>
		<emp-salary>90000</emp-salary>
		<emp-email>merinmg99@gmail.com</emp-email>
		<emp-phone>9847508465</emp-phone>
		<designation>Team Leader</designation>
		</employee>
		
	    <employee EMPID="eMP02">
		<emp-name>Ann Sherluck</emp-name>
		<emp-age>45</emp-age>
		<emp-salary>80000</emp-salary>
		<emp-email>merinmg99@gmail.com</emp-email>
		<emp-phone>9847508465</emp-phone>
		<designation>Team Leader</designation>
		</employee>
		
	    <employee EMPID="EMP03">
		<emp-name>Kevin George</emp-name>
		<emp-age>39</emp-age>
		<emp-salary>100000</emp-salary>
		<emp-email>merinmg99@gmail.com</emp-email>
		<emp-phone>9847508465</emp-phone>
		<designation>Team Leader</designation>
		</employee>
	
</Company>
